### ISSUE TITLE
请问是用黑果小兵的镜像吗？

### ISSUE THREAD

**Issue by ShawLocke** [ZzzM/Hackintosh-MSI-B360M-MORTAR#1]
10.15.7是用黑果小兵的镜像吗？

下载后是不是要用DiskGenius将其中的WEPE整个分区删掉？

请问有没有联系方式？昨晚装到2点都没成功？谢谢

**Comment by ZzzM** [comment]
@ShawLocke  我没有双系统要求，镜像（10.15.6）是自己制作的，然后一直无痛升级到  macOS Big Sur 11.0.1

**Comment by ShawLocke** [comment]
好的，谢谢回复。
