### ISSUE TITLE
oc 0.7.8 bigsur 11.6.4睡眠立即唤醒

### ISSUE THREAD

**Issue by 52shell** [ZzzM/Hackintosh-MSI-B360M-MORTAR#10]
![Xnip2022-03-01_23-36-39](https://user-images.githubusercontent.com/30046559/156199486-d2c66467-88fd-4ccf-8ea7-d1b7854ffa7a.jpg)

**Comment by 52shell** [comment]
![Xnip2022-03-01_23-39-03](https://user-images.githubusercontent.com/30046559/156199647-9c5cdffb-6747-401b-b7c1-34581a513373.jpg)

**Comment by 52shell** [comment]
找到问题 Alfred的问题。请问老哥在使用这个软件吗，

**Comment by ZzzM** [comment]
macOS 最新版本，Alfred 版本如下，睡眠唤醒正常
<img width="188" alt="image" src="https://user-images.githubusercontent.com/10611210/156926534-48af14b1-8575-4c7b-8363-6c4eee89e1f7.png">
