### ISSUE TITLE
thank you!! can i ask some thing that is my faced problem....

### ISSUE THREAD

**Issue by MAKER-park** [ZzzM/Hackintosh-MSI-B360M-MORTAR#11]
Thank you so much for providing a really nice file.
It was confirmed that Fenvi FV-T919 BCM94360CD device of the corresponding chipset was used for the driver for using ble and wifi.

So I also purchased the equipment for use as an airdrop sidecar.
Here is a link to the product you purchased.
https://en.aliexpress.com/item/32778371977.html?gatewayAdapt=glo2kor&spm=a2g0o.order_detail.0.0.31ac5ccdHRu3nh

The wifi is successfully caught well. However... the bluetooth function is not properly checked...
![스크린샷 2022-03-10 오후 2 29 24](https://user-images.githubusercontent.com/18068835/157595825-79aae5a6-69c8-422e-b5e3-1135070f4750.png)

If I am not buying the wrong thing, is there any other procedural way to use Bluetooth?

**Comment by ZzzM** [comment]
Sorry, I can't open the link to the product you provided.
 Here is a link to the product https://www.amazon.com/fenvi-Continuity-BCM94360CD-1750Mbps-Beamforming/dp/B07VCCZS54
