### ISSUE TITLE
请问Fenvi FV-T919网卡网速最高能达到多少？

### ISSUE THREAD

**Issue by thorxh** [ZzzM/Hackintosh-MSI-B360M-MORTAR#12]
首先，感谢提供的EFI。
我使用的相同网卡，网速最高只有2-3M/s，隔空投送也只有10M/s，老哥的上限是多少呢？

**Comment by ZzzM** [comment]
@thorxh 老哥，不好意思，我误关了这个仓库的通知提醒，今天才看到你的问题。
我刚测完，网速最高能跑到 6M/s，隔空投送 20M/s
