### ISSUE TITLE
使用occ，配置检查报错

### ISSUE THREAD

**Issue by reyukari** [ZzzM/Hackintosh-MSI-B360M-MORTAR#14]
注意: 此版本的 ocvalidate 仅兼容 OpenCore 版本 0.8.8!

警告: 缺少 CustomPciSerialDevice 键值, 位置: <Quirks>!
警告: 缺少 ForceAquantiaEthernet 键值, 位置: <Quirks>!
警告: 缺少 HibernateSkipsPicker 键值, 位置: <Boot>!
警告: 发现SerialInit选项在索引5处，此版本没有这个选项或已移动位置, 位置: <Debug>!
警告: 缺少 LogModules 键值, 位置: <Debug>!
警告: 发现AllowNvramReset选项在索引0处，此版本没有这个选项或已移动位置, 位置: <Security>!
警告: 发现AllowToggleSip选项在索引2处，此版本没有这个选项或已移动位置, 位置: <Security>!
警告: 缺少 FullNvramAccess 键值, 位置: <Tools>!
警告: 缺少 Serial 键值, 位置: <Misc>!
警告: 发现LegacyEnable选项在索引2处，此版本没有这个选项或已移动位置, 位置: <NVRAM>!
警告: 缺少 PointerDwellClickTimeout 键值, 位置: <AppleInput>!
警告: 缺少 PointerDwellDoubleClickTimeout 键值, 位置: <AppleInput>!
警告: 缺少 PointerDwellRadius 键值, 位置: <AppleInput>!
警告: 缺少 LoadEarly 键值, 位置: <Drivers>!
配置检查发现19个错误!

验证/Volumes/EFI/EFI/OC/config.plist用了1毫秒完成，发现19个问题需要注意.

**Comment by reyukari** [comment]
使用健壮性测试
Misc - Serial -->缺失此部分
Quirks
CustomPciSerialDevice -->缺失内容. 通常设置为 No
ForceAquantiaEthernet -->缺失内容. 通常设置为 No
Boot

**Comment by ZzzM** [comment]
@reyukari config 已更新
