### ISSUE TITLE
可以把oc里面的resource的资源文件补齐

### ISSUE THREAD

**Issue by reyukari** [ZzzM/Hackintosh-MSI-B360M-MORTAR#15]
用occ 的工具似乎会有网络问题，这里打包了一份
[font](https://eeete.fun:8000/d/share/Font.zip?sign=Gxl4-QKFqb1xhVs5HuMyMdwx0q9XL5OqfKd2NQsmyH0=:0)
[label](https://eeete.fun:8000/d/share/Label.zip?sign=Z96GGRxMzNpViuYeiDelZScO8FWmvcOC4g7JT99oFn4=:0)

增加一些好看的UI可以更易用

**Comment by ZzzM** [comment]
@reyukari 感谢反馈，这个是故意不放的，具体美化看个人需求。
