### ISSUE TITLE
引导oc下载的镜像失败 tag:3.2 3.1

### ISSUE THREAD

**Issue by failin98fish** [ZzzM/Hackintosh-MSI-B360M-MORTAR#16]
尝试了两种方法，使用oc下载的最新ventura镜像，oc引导能识别windows能识别EFI分区（external），但是回车后卡了一会又回到oc引导界面了，windows可以引导成功

使用恢复镜像烧录到upan，ventura13.2 13.1都试过了，但是引导界面只有windows和winpe 识别不到恢复镜像

bios设置参照了https://github.com/GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI
硬件都相同，但是显卡是蓝宝石rx590超白金
求大佬解

**Comment by ZzzM** [comment]
@failin98fish 抱歉，我只使用 macOS，未安装引导过双系统，你反馈的问题，没有遇到过。
不过根据你的描述，我找到几个类似的情况以及解决方法，希望对你有所帮助：
- https://hackintool.vercel.app/%E5%9F%BA%E7%A1%80%E7%AF%87/%E5%8F%8C%E7%B3%BB%E7%BB%9F.html
- https://github.com/GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI/issues/8
- https://www.v2ex.com/t/782878
