### ISSUE TITLE
网卡Fenvi FV-T919 BCM94360CD在Ventursa 13.5系统下的蓝牙信号强吗？

### ISSUE THREAD

**Issue by thorxh** [ZzzM/Hackintosh-MSI-B360M-MORTAR#18]
我的蓝牙信号很弱

**Comment by thorxh** [comment]
手机检测蓝牙信号强度，在-80到-100之间，蓝牙耳机连上后时断时续的，你没有这种情况吗？你的蓝牙离设备远不远？

**Comment by ZzzM** [comment]
我耳机是 AirPods ，没出现过时断时续。
测了一下，蓝牙离设备 80-90cm，强度 -60 左右

**Comment by thorxh** [comment]
你这个信号很强了，可能是我的设备有问题

**Comment by thorxh** [comment]
@ZzzM 多谢了，试了下，蓝牙信号强度没什么变化，应该是我的设备有问题，不用管了，后面再换个网卡
