### ISSUE TITLE
关于OC文件夹中的Resources文件夹

### ISSUE THREAD

**Issue by 4Nanai** [ZzzM/Hackintosh-MSI-B360M-MORTAR#2]
作者你好，请问这个文件夹您是否是忘记上传了？我这边用您的EFI文件安装黑苹果失败了，发现和其他人的相比少了Resources文件夹。

**Comment by ZzzM** [comment]
@4Nanai 多谢提醒，已补充提交。
我的EFI中 Resources 文件夹里面是空的，git 无法识别，导致不会上传。
