### ISSUE TITLE
老板啥时更新14.1

### ISSUE THREAD

**Issue by guange2015** [ZzzM/Hackintosh-MSI-B360M-MORTAR#20]
谢谢了

**Comment by ZzzM** [comment]
暂无计划，由于驱动限制，需借助 [OCLP](https://github.com/dortania/OpenCore-Legacy-Patcher) 完善。参考这位大佬 https://github.com/GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#20231112

**Comment by ZzzM** [comment]
不一定，看后续是否有其他方案实现
