### ISSUE TITLE
3.6.3安装的时候panic了，请问遇到吗

### ISSUE THREAD

**Issue by jarheadjoe** [ZzzM/Hackintosh-MSI-B360M-MORTAR#21]
panic(cpu 7 caller 0xffffff7f94f61c9b): assertmsg com.apple.AppleIntelController.cpp:29505
Panicked task 0xffffff9870ac9478: 155 threads: pid 0: kernel_task
Backtrace (CPU 7), panicked thread: 0xffffff9871140598, Frame : Return Address
0xffffffebce287940 : 0xffffff8013c7205d 
0xffffffebce287990 : 0xffffff8013dc6144 
0xffffffebce2879d0 : 0xffffff8013db5c57 
0xffffffebce287a20 : 0xffffff8013c12951 
0xffffffebce287a40 : 0xffffff8013c7233d 
0xffffffebce287b30 : 0xffffff8013c719e7 
0xffffffebce287b90 : 0xffffff80143db32b 
0xffffffebce287c80 : 0xffffff7f94f61c9b 
0xffffffebce287c90 : 0xffffff7f94f03bb5 
0xffffffebce287d00 : 0xffffff7f94f00118 
0xffffffebce287da0 : 0xffffff80142e7fb1 
0xffffffebce287e00 : 0xffffff80142e7b2a 
0xffffffebce287ec0 : 0xffffff80142e6bdf 
0xffffffebce287f20 : 0xffffff80142e9d6a 
0xffffffebce287fa0 : 0xffffff8013c1219e 
      Kernel Extensions in backtrace:
         com.apple.driver.AppleIntelCFLGraphicsFramebuffer(20.0.6)[38204761-5F6B-3734-99F4-E4C7B2C822C8]com.apple.0xffffff7f94ecd000-com.apple.driver.0xffffff7f94f92fff
            dependency: com.apple.AppleGraphicsDeviceControl(7.1.18)[B22B74AE-08E9-3D23-8F7A-EAD3C39EE7AD]com.apple.0xffffff7f94c4b000-com.apple.driver.0xffffff7f94c4efff
            dependency: com.apple.iokit.IOACPIFamily(1.4)[D342E754-A422-3F44-BFFB-DEE93F6723BC]com.apple.0xffffff801623c000-com.apple.driver.0xffffff801623dfff
            dependency: com.apple.iokit.IOAcceleratorFamily2(475.40.6)[5CEA519D-44FC-30EB-8622-2394570EBDD4]com.apple.0xffffff7f95874000-com.apple.driver.0xffffff7f958defff
            dependency: com.apple.iokit.IOGraphicsFamily(597)[718E01CF-8B05-3042-88F4-DE3441395D00]com.apple.0xffffff7f959c9000-com.apple.driver.0xffffff7f959f7fff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[F11A1D9C-398D-3933-94D6-9539D3B7B1FD]com.apple.0xffffff80166ac000-com.apple.driver.0xffffff80166ddfff
            dependency: com.apple.iokit.IOReportFamily(47)[491DDA55-D371-3A28-9A77-C28DB013D8AE]com.apple.0xffffff80166ee000-com.apple.driver.0xffffff80166f0fff

Process name corresponding to current thread (0xffffff9871140598): kernel_task
Boot args: shikigva=80 igfxfw=2 root-dmg=file:///BaseSystem/BaseSystem.dmg

Mac OS version:
22G120

Kernel version:
Darwin Kernel Version 22.6.0: Fri Sep 15 13:39:52 PDT 2023; root:xnu-8796.141.3.700.8~1/RELEASE_X86_64
Kernel UUID: F75FC53F-FC1A-3AB6-8980-EF66A83DD51D
roots installed: 0
KernelCache slide: 0x0000000013800000
KernelCache base:  0xffffff8013a00000
Kernel slide:      0x00000000138dc000
Kernel text base:  0xffffff8013adc000
__HIB  text base: 0xffffff8013900000
System model name: iMacPro1,1 (Mac-7BA5B2D9E42DDD94)
System shutdown begun: NO
Panic diags file unavailable, panic occurred prior to initialization
Hibernation exit count: 0

System uptime in nanoseconds: 31425604172
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x00000007511cad29
  Sleep   : 0x0000000000000000 0x0000000000000000 0x0000000000000000
  Wake    : 0x0000000000000000 0x00000017b2f44d0c 0x0000000000000000
Compressor Info: 0% of compressed pages limit (OK) and 0% of segments limit (OK) with 0 swapfiles and OK swap space
Zone info:
  Zone map: 0xffffff886ea48000 - 0xffffffa86ea48000
  . PGZ   : 0xffffff886ea48000 - 0xffffff8872a49000
  . VM    : 0xffffff8872a49000 - 0xffffff8d3ed7c000
  . RO    : 0xffffff8d3ed7c000 - 0xffffff8ed83e2000
  . GEN0  : 0xffffff8ed83e2000 - 0xffffff93a4715000
  . GEN1  : 0xffffff93a4715000 - 0xffffff9870a48000
  . GEN2  : 0xffffff9870a48000 - 0xffffff9d3cd7b000
  . GEN3  : 0xffffff9d3cd7b000 - 0xffffffa2090ae000
  . DATA  : 0xffffffa2090ae000 - 0xffffffa86ea48000
  Metadata: 0xffffff80375f2000 - 0xffffff80575f2000
  Bitmaps : 0xffffff80575f2000 - 0xffffff805d5f2000
  Extra   : 0 - 0

last started kext at 31425402524: com.apple.driver.AppleSMBusPCI	1.0.14d1 (addr 0xffffff7f956ce000, size 4096)
loaded kexts:
as.acidanthera.mieze.IntelMausi	1.0.8
ru.joedm.SMCSuperIO	1.3.3
as.vit9696.SMCProcessor	1.3.3
as.vit9696.VirtualSMC	1.3.3
org.acidanthera.NVMeFix	1.1.2
as.vit9696.AppleALC	1.8.9
as.vit9696.WhateverGreen	1.6.7
as.vit9696.Lilu	1.6.8
com.apple.driver.AppleGraphicsDevicePolicy	7.1.18
com.apple.AGDCPluginDisplayMetrics	7.1.18
com.apple.driver.pmtelemetry	1
com.apple.filesystems.nfs	1
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.driver.AppleHV	1
com.apple.driver.AppleDiskImages2	198.100.13
com.apple.driver.AppleIntelPCHPMC	2.0.1
com.apple.driver.AppleFIVRDriver	4.1.0
com.apple.driver.AppleIntelCFLGraphicsFramebuffer	20.0.6
com.apple.driver.ACPI_SMC_PlatformPlugin	1.0.0
com.apple.driver.AppleIntelMCEReporter	115
com.apple.driver.AppleIntelSlowAdaptiveClocking	4.0.0
com.apple.driver.DiskImages.SparseDiskImage	493.0.0
com.apple.driver.DiskImages.ReadWriteDiskImage	493.0.0
com.apple.driver.DiskImages.UDIFDiskImage	493.0.0
com.apple.driver.DiskImages.RAMBackingStore	493.0.0
com.apple.driver.DiskImages.HTTPBackingStore	493.0.0
com.apple.driver.DiskImages.FileBackingStore	493.0.0
com.apple.iokit.SCSITaskUserClient	482.120.2
com.apple.driver.AppleUSBMassStorageInterfaceNub	554
com.apple.driver.AppleFileSystemDriver	3.0.1
com.apple.filesystems.tmpfs	1
com.apple.filesystems.lifs	1
com.apple.filesystems.apfs	2142.140.9
com.apple.filesystems.hfs.kext	627.100.6
com.apple.BootCache	40
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.private.KextAudit	1.0
com.apple.driver.AppleAHCIPort	378
com.apple.driver.AppleACPIButtons	6.1
com.apple.driver.AppleRTC	2.0.1
com.apple.driver.AppleHPET	1.8
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleAPIC	1.7
com.apple.security.AppleUserConsent	1
com.apple.AppleSystemPolicy	2.0.0
com.apple.nke.applicationfirewall	404
com.apple.iokit.IOKitRegistryCompatibility	1
com.apple.iokit.EndpointSecurity	1
com.apple.Dont_Steal_Mac_OS_X	7.0.0
com.apple.kec.Compression	1
com.apple.kec.AppleEncryptedArchive	1
com.apple.driver.AppleSMBusPCI	1.0.14d1
com.apple.driver.AppleGraphicsControl	7.1.18
com.apple.kext.triggers	1.0
com.apple.iokit.IOBluetoothSerialManager	9.0.0
com.apple.iokit.CSRBluetoothHostControllerUSBTransport	9.0.0
com.apple.iokit.BroadcomBluetooth20703USBTransport	9.0.0
com.apple.iokit.IONDRVSupport	597
com.apple.iokit.IOAcceleratorFamily2	475.40.6
com.apple.driver.IOPlatformPluginLegacy	1.0.0
com.apple.driver.X86PlatformPlugin	1.0.0
com.apple.driver.IOPlatformPluginFamily	6.0.0d8
com.apple.AppleGPUWrangler	7.1.18
com.apple.AppleGraphicsDeviceControl	7.1.18
com.apple.iokit.IOGraphicsFamily	597
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.driver.DiskImages.KernelBacked	493.0.0
com.apple.iokit.IOAHCIBlockStorage	350.140.3
com.apple.driver.AppleXsanScheme	3
com.apple.driver.usb.AppleUSBHub	1.2
com.apple.driver.usb.IOUSBHostHIDDevice	1.2
com.apple.driver.usb.cdc	5.0.0
com.apple.driver.usb.networking	5.0.0
com.apple.driver.usb.AppleUSBHostCompositeDevice	1.2
com.apple.driver.AppleBSDKextStarter	3
com.apple.iokit.IOSurface	336.60.1
com.apple.filesystems.hfs.encodings.kext	1
com.apple.driver.AppleSyntheticGameController	10.7.1
com.apple.driver.AppleEFINVRAM	2.1
com.apple.driver.usb.AppleUSBHostPacketFilter	1.0
com.apple.iokit.IOUSBFamily	900.4.2
com.apple.driver.usb.AppleUSBXHCIPCI	1.2
com.apple.driver.usb.AppleUSBXHCI	1.2
com.apple.iokit.IOAHCIFamily	301.100.1
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.driver.AppleEFIRuntime	2.1
com.apple.iokit.IOTimeSyncFamily	1150.2
com.apple.iokit.IOSkywalkFamily	1.0
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.iokit.IONetworkingFamily	3.4
com.apple.driver.DiskImages	493.0.0
com.apple.iokit.IOBluetoothFamily	9.0.0
com.apple.iokit.IOReportFamily	47
com.apple.security.quarantine	4
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.driver.AppleSSE	1.0
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleUSBTDM	554
com.apple.iokit.IOUSBMassStorageDriver	235.140.2
com.apple.iokit.IOSCSIBlockCommandsDevice	482.120.2
com.apple.iokit.IOStorageFamily	2.1
com.apple.iokit.IOSCSIArchitectureModelFamily	482.120.2
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleEffaceableStorage	1.0
com.apple.driver.AppleCyrus	1
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.security.AppleImage4	5.0.0
com.apple.kext.CoreTrust	1
com.apple.driver.AppleCredentialManager	1.0
com.apple.iokit.CoreAnalyticsFamily	1
com.apple.driver.KernelRelayHost	1
com.apple.iokit.IOUSBHostFamily	1.2
com.apple.driver.AppleUSBHostMergeProperties	1.2
com.apple.driver.usb.AppleUSBCommon	1.0
com.apple.driver.AppleBusPowerController	1.0
com.apple.driver.AppleSEPManager	1.0.1
com.apple.driver.IOSlaveProcessor	1
com.apple.driver.AppleACPIPlatform	6.1
com.apple.driver.AppleSMC	3.1.9
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.driver.watchdog	1
com.apple.kec.pthread	1
com.apple.kec.Libm	1
com.apple.kec.corecrypto	12.0

**Comment by ZzzM** [comment]
暂未遇到
