### ISSUE TITLE
EFI作者进来下，win+MacOS同时用的话，主板设置的教程有个设置有问题。

### ISSUE THREAD

**Issue by iwsbiwy** [ZzzM/Hackintosh-MSI-B360M-MORTAR#23]
@ZzzM 
主板BIOS版本7B23v1C，win系统版本是win10 ltsc 2019，MacOS版本是14.5。
我测试发现主板的“windows 10 WHQL支持”如果按教程设置为开启，装好MacOS后就进不去了，会卡在选择硬盘的界面，设置为关闭就解决了。
可以的话麻烦在EFI说明文件里注明一下，避免别人出现我同样的问题。谢谢。
![183057wtlfob97tcikb6nt.png](https://s2.loli.net/2024/05/31/ZPq3hpo8RT5SsVj.png)
![_20240531093658.jpg](https://s2.loli.net/2024/05/31/9W6NRy4cj5wmldt.jpg)

**Comment by ZzzM** [comment]
目前EFI未考虑双系统安装问题，感谢反馈
