### ISSUE TITLE
老哥,big sure 11.6用的什么镜像?

### ISSUE THREAD

**Issue by ChinaDragonNB** [ZzzM/Hackintosh-MSI-B360M-MORTAR#4]
我用黑苹果小兵的三分区镜像,EFI替换成你的后,是这样的

https://s3.bmp.ovh/imgs/2021/09/024e5467c7e036e3.jpg

**Comment by zhangan115** [comment]
@ChinaDragonNB  这个是OpenCode的黑苹果，如果你和他的硬件差不多，就直接去OC官网按照教程做u盘镜像。替换EFI文件就可以 了

**Comment by ChinaDragonNB** [comment]
> @ChinaDragonNB 这个是OpenCode的黑苹果，如果你和他的硬件差不多，就直接去OC官网按照教程做u盘镜像。替换EFI文件就可以 了

好的，谢谢。
