### ISSUE TITLE
11.6.1和12.1  efi使用无法识别dmg

### ISSUE THREAD

**Issue by 52shell** [ZzzM/Hackintosh-MSI-B360M-MORTAR#5]
你好，大佬，最近12.1和11.6.1的efi用oc下载dmg镜像，在引导页面识别不到dmg镜像。11.6版本可以正常安装

**Comment by ZzzM** [comment]
> 你好，大佬，最近12.1和11.6.1的efi用oc下载dmg镜像，在引导页面识别不到dmg镜像。11.6版本可以正常安装

config.plist  更新了吗？

**Comment by 52shell** [comment]
更新了

**Comment by 52shell** [comment]
拉取大佬最新efi文件

**Comment by 52shell** [comment]
opencore拉取镜像是根据大佬的efi文件所示版本

**Comment by ZzzM** [comment]
你说的镜像是指 系统镜像？

**Comment by 52shell** [comment]
py爬取的dmg镜像

**Comment by 52shell** [comment]
根据opencore的教程拉取的镜像

**Comment by ZzzM** [comment]
你现在系统版本 12.1？

**Comment by 52shell** [comment]
11.6

**Comment by 52shell** [comment]
我的硬盘坏了 用的新新盘装的

**Comment by ZzzM** [comment]
理论上，直接拉去最新的EFI去替换你的，保留自己的config.plist 就行了

**Comment by 52shell** [comment]
具体表现是:正常写入u盘。拉取dmg镜像  efi文件修改config，电脑重启u盘启动到达oc引导界面选择安装.确定之后还是跳回oc引导界面。不显示dmg选项

**Comment by 52shell** [comment]
是的，以前也是这样

**Comment by ZzzM** [comment]
能通过检查更新实现升级吗

**Comment by 52shell** [comment]
我晚上试一试

**Comment by ZzzM** [comment]
这是我系统升级的操作：先备份 EFI 到U盘，升级本地 EFI 中的OC、扩展等，然后直接检查更新升级系统，有时候可能检查不到系统更新，可以通过 App Store 直接下载系统安装

**Comment by 52shell** [comment]
好的 ，谢谢大佬解答！

**Comment by 52shell** [comment]
11.6正常升级为11.6.2 用的11.6.1的efi暂不知道有没有问题
