### ISSUE TITLE
不知道有没有在用Apple Watch解锁的

### ISSUE THREAD

**Issue by milesking** [ZzzM/Hackintosh-MSI-B360M-MORTAR#6]
这块板子的Apple Watch解锁几乎无法正常使用，刚打开选项的时候有可能能用，但是过段时间就不行了（一小会儿）。用华硕b360i不用配置就是正常的。不知道你那边有没有在用这个功能，是不是正常的。

**Comment by ZzzM** [comment]
目前没有 Apple Watch 测试

**Comment by milesking** [comment]
有很多教程说需要关Super IO，但是我找遍了BIOS，好像没有

**Comment by ZzzM** [comment]
我看了一下官方介绍 https://support.apple.com/zh-cn/HT206995

理由上我的配置是支持 Apple Watch 解锁的

<img width="417" alt="image" src="https://user-images.githubusercontent.com/10611210/155322761-61023ae5-88d7-4679-98ad-6064cff0ed04.png">

**Comment by milesking** [comment]
理论上是支持的，实际上刚勾选Apple Watch解锁的时候也是能用的。但是过段时间，比如锁屏一段时间后就失效了，这个时间不固定。不是配置的问题，我看了很多帖子，基本都指向BIOS的super IO选项，但是这块板子的BIOS里没有。肯定不是EFI的问题，我自己搞的，包括用的其他的EFI配置都是一样。四代U微星主板也有这个问题，我试了华硕的板子，每次都能成功，四代和八代华硕都可以
