### ISSUE TITLE
你好,请问你的这一套配置花了多少钱?

### ISSUE THREAD

**Issue by Misakei** [ZzzM/Hackintosh-MSI-B360M-MORTAR#7]
你的这一套配置花了多少钱?打算在价格和兼容性之间权衡一下,要是价格不是差特别多的话,就买iMac了

**Comment by ZzzM** [comment]
这套配置购于2019年，不含外设，五千以内。配置应该过时了，目前最流行配置价格不大清楚。

**Comment by Misakei** [comment]
好的,谢谢啊
