### ISSUE TITLE
请问有遇到过 宗卷哈希值不匹配 这个错误的吗

### ISSUE THREAD

**Issue by guange2015** [ZzzM/Hackintosh-MSI-B360M-MORTAR#9]
昨天开机时弹出这个提示，然后机器变卡，跳到重新登录界面，继续卡
今天准备抹盘重装，重新进入又没这个问题了

**Comment by ZzzM** [comment]
目前没出现过这种问题，我搜了一下，看到 [这个帖子](https://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1920733)，希望对你有帮助

**Comment by guange2015** [comment]
谢谢，这些资料我都试过了，现在没办法，准备抹盘重装

**Comment by guange2015** [comment]
还有，@zzzM大，可以帮我看下我重装的方法对吗

下载苹果小兵做好的镜然，然后把这边的oc efi直接替换进去。  现在进去后看到不安装mac这一项，下一步被卡住了

**Comment by ZzzM** [comment]
默认的 OC EFI 能正常安装吗？如果能正常安装，进入系统后，再替换硬盘的 EFI 看看

**Comment by 52shell** [comment]
> 还有，@ZzzM大，可以帮我看我重装的方法，对吗？
> 
> 下载苹果小兵的镜片，然后直接替换oc efi。现在，在看到不安装Mac后进去，下一步被卡住了

同出现相同问题，不过11.6是可以正常引导的，蒙特雷12.2.1也可以，11.6.1是不能引导，但是正常升级是可以引导进系统
